#!/usr/bin/env ol

(import (file json))

(define PREFIX "es")

(print "#pragma once

/* This file is autogenerated! Do not edit. */

#include <GL/gl.h>

")

(define json (read-json stdin))
(ff-for-each (lambda (name arguments)
      (define return (ref arguments 1))
      (define args (cdr (vector->list arguments)))

      ;; external function
      (for-each display (list "extern " return " " "(* " PREFIX (substring (symbol->string name) 2) ")"))
      (display "(")
      (unless (null? args)
         (let loop ((args args))
            (display (car args))
            (unless (null? (cdr args))
               (display ", ")
               (loop (cdr args)))))
      (print ");"))
   json)
