/* This file is autogenerated! Do not edit. */
#include "es.h"

#include "log.h"

//
void (* esGetIntegerv)(GLenum pname, GLint * params) = 0;
__attribute__((visibility("default")))
void glGetIntegerv(
    GLenum pname, 
    GLint * params);
//
void (* esDeleteRenderbuffers)(GLsizei n, const GLuint * renderbuffers) = 0;
__attribute__((visibility("default")))
void glDeleteRenderbuffers(
    GLsizei n, 
    const GLuint * renderbuffers)
{
   (void) esDeleteRenderbuffers(n, renderbuffers);
}
//
void (* esClear)(GLbitfield mask) = 0;
__attribute__((visibility("default")))
void glClear(
    GLbitfield mask)
{
   (void) esClear(mask);
}
//
void (* esBlendColor)(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) = 0;
__attribute__((visibility("default")))
void glBlendColor(
    GLclampf red, 
    GLclampf green, 
    GLclampf blue, 
    GLclampf alpha)
{
   (void) esBlendColor(red, green, blue, alpha);
}
//
void (* esBindBuffer)(GLenum target, GLuint buffer) = 0;
__attribute__((visibility("default")))
void glBindBuffer(
    GLenum target, 
    GLuint buffer)
{
   (void) esBindBuffer(target, buffer);
}
//
void (* esAttachShader)(GLuint program, GLuint shader) = 0;
__attribute__((visibility("default")))
void glAttachShader(
    GLuint program, 
    GLuint shader)
{
   (void) esAttachShader(program, shader);
}
//
void (* esActiveTexture)(GLenum texture) = 0;
__attribute__((visibility("default")))
void glActiveTexture(
    GLenum texture);
//
void (* esBindAttribLocation)(GLuint program, GLuint index, const GLchar * name) = 0;
__attribute__((visibility("default")))
void glBindAttribLocation(
    GLuint program, 
    GLuint index, 
    const GLchar * name)
{
   (void) esBindAttribLocation(program, index, name);
}
//
void (* esBindRenderbuffer)(GLenum target, GLuint renderbuffer) = 0;
__attribute__((visibility("default")))
void glBindRenderbuffer(
    GLenum target, 
    GLuint renderbuffer)
{
   (void) esBindRenderbuffer(target, renderbuffer);
}
//
void (* esBindFramebuffer)(GLenum target, GLuint framebuffer) = 0;
__attribute__((visibility("default")))
void glBindFramebuffer(
    GLenum target, 
    GLuint framebuffer)
{
   (void) esBindFramebuffer(target, framebuffer);
}
//
void (* esBindTexture)(GLenum target, GLuint texture) = 0;
__attribute__((visibility("default")))
void glBindTexture(
    GLenum target, 
    GLuint texture)
{
   (void) esBindTexture(target, texture);
}
//
void (* esBlendFuncSeparate)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha) = 0;
__attribute__((visibility("default")))
void glBlendFuncSeparate(
    GLenum sfactorRGB, 
    GLenum dfactorRGB, 
    GLenum sfactorAlpha, 
    GLenum dfactorAlpha)
{
   (void) esBlendFuncSeparate(sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha);
}
//
void (* esBlendEquationSeparate)(GLenum modeRGB, GLenum modeA) = 0;
__attribute__((visibility("default")))
void glBlendEquationSeparate(
    GLenum modeRGB, 
    GLenum modeA)
{
   (void) esBlendEquationSeparate(modeRGB, modeA);
}
//
void (* esBlendEquation)(GLenum mode) = 0;
__attribute__((visibility("default")))
void glBlendEquation(
    GLenum mode)
{
   (void) esBlendEquation(mode);
}
//
void (* esBlendFunc)(GLenum sfactor, GLenum dfactor) = 0;
__attribute__((visibility("default")))
void glBlendFunc(
    GLenum sfactor, 
    GLenum dfactor)
{
   (void) esBlendFunc(sfactor, dfactor);
}
//
void (* esBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid * data) = 0;
__attribute__((visibility("default")))
void glBufferSubData(
    GLenum target, 
    GLintptr offset, 
    GLsizeiptr size, 
    const GLvoid * data)
{
   (void) esBufferSubData(target, offset, size, data);
}
//
void (* esBufferData)(GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage) = 0;
__attribute__((visibility("default")))
void glBufferData(
    GLenum target, 
    GLsizeiptr size, 
    const GLvoid * data, 
    GLenum usage)
{
   (void) esBufferData(target, size, data, usage);
}
//
GLenum (* esCheckFramebufferStatus)(GLenum target) = 0;
__attribute__((visibility("default")))
GLenum glCheckFramebufferStatus(
    GLenum target)
{
   return esCheckFramebufferStatus(target);
}
//
void (* esCopyTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) = 0;
__attribute__((visibility("default")))
void glCopyTexImage2D(
    GLenum target, 
    GLint level, 
    GLenum internalformat, 
    GLint x, 
    GLint y, 
    GLsizei width, 
    GLsizei height, 
    GLint border)
{
   (void) esCopyTexImage2D(target, level, internalformat, x, y, width, height, border);
}
//
void (* esColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) = 0;
__attribute__((visibility("default")))
void glColorMask(
    GLboolean red, 
    GLboolean green, 
    GLboolean blue, 
    GLboolean alpha)
{
   (void) esColorMask(red, green, blue, alpha);
}
//
void (* esClearDepthf)(GLclampf depth) = 0;
__attribute__((visibility("default")))
void glClearDepthf(
    GLclampf depth)
{
   (void) esClearDepthf(depth);
}
//
void (* esClearColor)(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) = 0;
__attribute__((visibility("default")))
void glClearColor(
    GLclampf red, 
    GLclampf green, 
    GLclampf blue, 
    GLclampf alpha)
{
   (void) esClearColor(red, green, blue, alpha);
}
//
void (* esClearStencil)(GLint s) = 0;
__attribute__((visibility("default")))
void glClearStencil(
    GLint s)
{
   (void) esClearStencil(s);
}
//
void (* esCompressedTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data) = 0;
__attribute__((visibility("default")))
void glCompressedTexImage2D(
    GLenum target, 
    GLint level, 
    GLenum internalformat, 
    GLsizei width, 
    GLsizei height, 
    GLint border, 
    GLsizei imageSize, 
    const GLvoid * data)
{
   (void) esCompressedTexImage2D(target, level, internalformat, width, height, border, imageSize, data);
}
//
void (* esCompileShader)(GLuint shader) = 0;
__attribute__((visibility("default")))
void glCompileShader(
    GLuint shader)
{
   (void) esCompileShader(shader);
}
//
void (* esCompressedTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data) = 0;
__attribute__((visibility("default")))
void glCompressedTexSubImage2D(
    GLenum target, 
    GLint level, 
    GLint xoffset, 
    GLint yoffset, 
    GLsizei width, 
    GLsizei height, 
    GLenum format, 
    GLsizei imageSize, 
    const GLvoid * data)
{
   (void) esCompressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, data);
}
//
void (* esCullFace)(GLenum mode) = 0;
__attribute__((visibility("default")))
void glCullFace(
    GLenum mode)
{
   (void) esCullFace(mode);
}
//
GLuint (* esCreateProgram)() = 0;
__attribute__((visibility("default")))
GLuint glCreateProgram(
)
{
   return esCreateProgram();
}
//
void (* esCopyTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) = 0;
__attribute__((visibility("default")))
void glCopyTexSubImage2D(
    GLenum target, 
    GLint level, 
    GLint xoffset, 
    GLint yoffset, 
    GLint x, 
    GLint y, 
    GLsizei width, 
    GLsizei height)
{
   (void) esCopyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height);
}
//
GLuint (* esCreateShader)(GLenum type) = 0;
__attribute__((visibility("default")))
GLuint glCreateShader(
    GLenum type)
{
   return esCreateShader(type);
}
//
void (* esDeleteFramebuffers)(GLsizei n, const GLuint * framebuffers) = 0;
__attribute__((visibility("default")))
void glDeleteFramebuffers(
    GLsizei n, 
    const GLuint * framebuffers)
{
   (void) esDeleteFramebuffers(n, framebuffers);
}
//
void (* esDeleteBuffers)(GLsizei n, const GLuint * buffer) = 0;
__attribute__((visibility("default")))
void glDeleteBuffers(
    GLsizei n, 
    const GLuint * buffer)
{
   (void) esDeleteBuffers(n, buffer);
}
//
void (* esDeleteProgram)(GLuint program) = 0;
__attribute__((visibility("default")))
void glDeleteProgram(
    GLuint program)
{
   (void) esDeleteProgram(program);
}
//
void (* esFramebufferTexture2D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) = 0;
__attribute__((visibility("default")))
void glFramebufferTexture2D(
    GLenum target, 
    GLenum attachment, 
    GLenum textarget, 
    GLuint texture, 
    GLint level)
{
   (void) esFramebufferTexture2D(target, attachment, textarget, texture, level);
}
//
void (* esDisableVertexAttribArray)(GLuint index) = 0;
__attribute__((visibility("default")))
void glDisableVertexAttribArray(
    GLuint index)
{
   (void) esDisableVertexAttribArray(index);
}
//
void (* esDepthMask)(GLboolean flag) = 0;
__attribute__((visibility("default")))
void glDepthMask(
    GLboolean flag)
{
   (void) esDepthMask(flag);
}
//
void (* esDeleteTextures)(GLsizei n, const GLuint * textures) = 0;
__attribute__((visibility("default")))
void glDeleteTextures(
    GLsizei n, 
    const GLuint * textures)
{
   (void) esDeleteTextures(n, textures);
}
//
void (* esDeleteShader)(GLuint program) = 0;
__attribute__((visibility("default")))
void glDeleteShader(
    GLuint program)
{
   (void) esDeleteShader(program);
}
//
void (* esDepthFunc)(GLenum func) = 0;
__attribute__((visibility("default")))
void glDepthFunc(
    GLenum func)
{
   (void) esDepthFunc(func);
}
//
void (* esDetachShader)(GLuint program, GLuint shader) = 0;
__attribute__((visibility("default")))
void glDetachShader(
    GLuint program, 
    GLuint shader)
{
   (void) esDetachShader(program, shader);
}
//
void (* esDepthRangef)(GLclampf zNear, GLclampf zFar) = 0;
__attribute__((visibility("default")))
void glDepthRangef(
    GLclampf zNear, 
    GLclampf zFar)
{
   (void) esDepthRangef(zNear, zFar);
}
//
void (* esDisable)(GLenum cap) = 0;
__attribute__((visibility("default")))
void glDisable(
    GLenum cap)
{
   (void) esDisable(cap);
}
//
void (* esEnableVertexAttribArray)(GLuint index) = 0;
__attribute__((visibility("default")))
void glEnableVertexAttribArray(
    GLuint index)
{
   (void) esEnableVertexAttribArray(index);
}
//
void (* esDrawElements)(GLenum mode, GLsizei count, GLenum type, const GLvoid * indices) = 0;
__attribute__((visibility("default")))
void glDrawElements(
    GLenum mode, 
    GLsizei count, 
    GLenum type, 
    const GLvoid * indices)
{
   (void) esDrawElements(mode, count, type, indices);
}
//
void (* esDrawArrays)(GLenum mode, GLint first, GLsizei count) = 0;
__attribute__((visibility("default")))
void glDrawArrays(
    GLenum mode, 
    GLint first, 
    GLsizei count)
{
   (void) esDrawArrays(mode, first, count);
}
//
void (* esEnable)(GLenum cap) = 0;
__attribute__((visibility("default")))
void glEnable(
    GLenum cap)
{
   (void) esEnable(cap);
}
//
void (* esFlush)() = 0;
__attribute__((visibility("default")))
void glFlush(
)
{
   (void) esFlush();
}
//
void (* esFinish)() = 0;
__attribute__((visibility("default")))
void glFinish(
)
{
   (void) esFinish();
}
//
void (* esFramebufferRenderbuffer)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) = 0;
__attribute__((visibility("default")))
void glFramebufferRenderbuffer(
    GLenum target, 
    GLenum attachment, 
    GLenum renderbuffertarget, 
    GLuint renderbuffer)
{
   (void) esFramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer);
}
//
void (* esGetActiveUniform)(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, GLenum * type, GLchar * name) = 0;
__attribute__((visibility("default")))
void glGetActiveUniform(
    GLuint program, 
    GLuint index, 
    GLsizei bufSize, 
    GLsizei * length, 
    GLint * size, 
    GLenum * type, 
    GLchar * name)
{
   (void) esGetActiveUniform(program, index, bufSize, length, size, type, name);
}
//
void (* esGenRenderbuffers)(GLsizei n, GLuint * renderbuffers) = 0;
__attribute__((visibility("default")))
void glGenRenderbuffers(
    GLsizei n, 
    GLuint * renderbuffers)
{
   (void) esGenRenderbuffers(n, renderbuffers);
}
//
void (* esGenBuffers)(GLsizei n, GLuint * buffer) = 0;
__attribute__((visibility("default")))
void glGenBuffers(
    GLsizei n, 
    GLuint * buffer)
{
   (void) esGenBuffers(n, buffer);
}
//
void (* esFrontFace)(GLenum mode) = 0;
__attribute__((visibility("default")))
void glFrontFace(
    GLenum mode)
{
   (void) esFrontFace(mode);
}
//
void (* esGenFramebuffers)(GLsizei n, GLuint * framebuffers) = 0;
__attribute__((visibility("default")))
void glGenFramebuffers(
    GLsizei n, 
    GLuint * framebuffers)
{
   (void) esGenFramebuffers(n, framebuffers);
}
//
void (* esGenerateMipmap)(GLenum target) = 0;
__attribute__((visibility("default")))
void glGenerateMipmap(
    GLenum target)
{
   (void) esGenerateMipmap(target);
}
//
void (* esGenTextures)(GLsizei n, GLuint * textures) = 0;
__attribute__((visibility("default")))
void glGenTextures(
    GLsizei n, 
    GLuint * textures)
{
   (void) esGenTextures(n, textures);
}
//
void (* esGetActiveAttrib)(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, GLenum * type, GLchar * name) = 0;
__attribute__((visibility("default")))
void glGetActiveAttrib(
    GLuint program, 
    GLuint index, 
    GLsizei bufSize, 
    GLsizei * length, 
    GLint * size, 
    GLenum * type, 
    GLchar * name)
{
   (void) esGetActiveAttrib(program, index, bufSize, length, size, type, name);
}
//
void (* esGetBufferParameteriv)(GLenum target, GLenum pname, GLint * params) = 0;
__attribute__((visibility("default")))
void glGetBufferParameteriv(
    GLenum target, 
    GLenum pname, 
    GLint * params)
{
   (void) esGetBufferParameteriv(target, pname, params);
}
//
GLint (* esGetAttribLocation)(GLuint program, const GLchar * name) = 0;
__attribute__((visibility("default")))
GLint glGetAttribLocation(
    GLuint program, 
    const GLchar * name)
{
   return esGetAttribLocation(program, name);
}
//
void (* esGetAttachedShaders)(GLuint program, GLsizei maxCount, GLsizei * count, GLuint * obj) = 0;
__attribute__((visibility("default")))
void glGetAttachedShaders(
    GLuint program, 
    GLsizei maxCount, 
    GLsizei * count, 
    GLuint * obj)
{
   (void) esGetAttachedShaders(program, maxCount, count, obj);
}
//
void (* esGetBooleanv)(GLenum pname, GLboolean * params) = 0;
__attribute__((visibility("default")))
void glGetBooleanv(
    GLenum pname, 
    GLboolean * params)
{
   (void) esGetBooleanv(pname, params);
}
//
void (* esGetFloatv)(GLenum pname, GLfloat * params) = 0;
__attribute__((visibility("default")))
void glGetFloatv(
    GLenum pname, 
    GLfloat * params);
//
GLenum (* esGetError)() = 0;
__attribute__((visibility("default")))
GLenum glGetError(
)
{
   return esGetError();
}
//
void (* esGetFramebufferAttachmentParameteriv)(GLenum target, GLenum attachment, GLenum pname, GLint * params) = 0;
__attribute__((visibility("default")))
void glGetFramebufferAttachmentParameteriv(
    GLenum target, 
    GLenum attachment, 
    GLenum pname, 
    GLint * params)
{
   (void) esGetFramebufferAttachmentParameteriv(target, attachment, pname, params);
}
//
void (* esSampleCoverage)(GLclampf value, GLboolean invert) = 0;
__attribute__((visibility("default")))
void glSampleCoverage(
    GLclampf value, 
    GLboolean invert)
{
   (void) esSampleCoverage(value, invert);
}
//
void (* esGetVertexAttribiv)(GLuint index, GLenum pname, GLint * params) = 0;
__attribute__((visibility("default")))
void glGetVertexAttribiv(
    GLuint index, 
    GLenum pname, 
    GLint * params)
{
   (void) esGetVertexAttribiv(index, pname, params);
}
//
const GLubyte * (* esGetString)(GLenum name) = 0;
__attribute__((visibility("default")))
const GLubyte * glGetString(
    GLenum name)
{
   return esGetString(name);
}
//
void (* esGetShaderInfoLog)(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog) = 0;
__attribute__((visibility("default")))
void glGetShaderInfoLog(
    GLuint shader, 
    GLsizei bufSize, 
    GLsizei * length, 
    GLchar * infoLog)
{
   (void) esGetShaderInfoLog(shader, bufSize, length, infoLog);
}
//
void (* esGetProgramiv)(GLuint program, GLenum pname, GLint * params) = 0;
__attribute__((visibility("default")))
void glGetProgramiv(
    GLuint program, 
    GLenum pname, 
    GLint * params)
{
   (void) esGetProgramiv(program, pname, params);
}
//
void (* esGetProgramInfoLog)(GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog) = 0;
__attribute__((visibility("default")))
void glGetProgramInfoLog(
    GLuint program, 
    GLsizei bufSize, 
    GLsizei * length, 
    GLchar * infoLog)
{
   (void) esGetProgramInfoLog(program, bufSize, length, infoLog);
}
//
void (* esGetRenderbufferParameteriv)(GLenum target, GLenum pname, GLint * params) = 0;
__attribute__((visibility("default")))
void glGetRenderbufferParameteriv(
    GLenum target, 
    GLenum pname, 
    GLint * params)
{
   (void) esGetRenderbufferParameteriv(target, pname, params);
}
//
void (* esGetShaderSource)(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * source) = 0;
__attribute__((visibility("default")))
void glGetShaderSource(
    GLuint shader, 
    GLsizei bufSize, 
    GLsizei * length, 
    GLchar * source)
{
   (void) esGetShaderSource(shader, bufSize, length, source);
}
//
void (* esGetShaderPrecisionFormat)(GLenum shadertype, GLenum precisiontype, GLint * range, GLint * precision) = 0;
__attribute__((visibility("default")))
void glGetShaderPrecisionFormat(
    GLenum shadertype, 
    GLenum precisiontype, 
    GLint * range, 
    GLint * precision)
{
   (void) esGetShaderPrecisionFormat(shadertype, precisiontype, range, precision);
}
//
void (* esGetShaderiv)(GLuint shader, GLenum pname, GLint * params) = 0;
__attribute__((visibility("default")))
void glGetShaderiv(
    GLuint shader, 
    GLenum pname, 
    GLint * params)
{
   (void) esGetShaderiv(shader, pname, params);
}
//
void (* esGetUniformfv)(GLuint program, GLint location, GLfloat * params) = 0;
__attribute__((visibility("default")))
void glGetUniformfv(
    GLuint program, 
    GLint location, 
    GLfloat * params)
{
   (void) esGetUniformfv(program, location, params);
}
//
void (* esGetTexParameteriv)(GLenum target, GLenum pname, GLint * params) = 0;
__attribute__((visibility("default")))
void glGetTexParameteriv(
    GLenum target, 
    GLenum pname, 
    GLint * params)
{
   (void) esGetTexParameteriv(target, pname, params);
}
//
void (* esGetTexParameterfv)(GLenum target, GLenum pname, GLfloat * params) = 0;
__attribute__((visibility("default")))
void glGetTexParameterfv(
    GLenum target, 
    GLenum pname, 
    GLfloat * params)
{
   (void) esGetTexParameterfv(target, pname, params);
}
//
GLint (* esGetUniformLocation)(GLuint program, const GLchar * name) = 0;
__attribute__((visibility("default")))
GLint glGetUniformLocation(
    GLuint program, 
    const GLchar * name)
{
   return esGetUniformLocation(program, name);
}
//
void (* esGetVertexAttribPointerv)(GLuint index, GLenum pname, GLvoid ** pointer) = 0;
__attribute__((visibility("default")))
void glGetVertexAttribPointerv(
    GLuint index, 
    GLenum pname, 
    GLvoid ** pointer)
{
   (void) esGetVertexAttribPointerv(index, pname, pointer);
}
//
void (* esGetUniformiv)(GLuint program, GLint location, GLint * params) = 0;
__attribute__((visibility("default")))
void glGetUniformiv(
    GLuint program, 
    GLint location, 
    GLint * params)
{
   (void) esGetUniformiv(program, location, params);
}
//
void (* esGetVertexAttribfv)(GLuint index, GLenum pname, GLfloat * params) = 0;
__attribute__((visibility("default")))
void glGetVertexAttribfv(
    GLuint index, 
    GLenum pname, 
    GLfloat * params)
{
   (void) esGetVertexAttribfv(index, pname, params);
}
//
GLboolean (* esIsTexture)(GLuint texture) = 0;
__attribute__((visibility("default")))
GLboolean glIsTexture(
    GLuint texture)
{
   return esIsTexture(texture);
}
//
GLboolean (* esIsFramebuffer)(GLuint framebuffer) = 0;
__attribute__((visibility("default")))
GLboolean glIsFramebuffer(
    GLuint framebuffer)
{
   return esIsFramebuffer(framebuffer);
}
//
GLboolean (* esIsBuffer)(GLuint buffer) = 0;
__attribute__((visibility("default")))
GLboolean glIsBuffer(
    GLuint buffer)
{
   return esIsBuffer(buffer);
}
//
void (* esHint)(GLenum target, GLenum mode) = 0;
__attribute__((visibility("default")))
void glHint(
    GLenum target, 
    GLenum mode);
//
GLboolean (* esIsEnabled)(GLenum cap) = 0;
__attribute__((visibility("default")))
GLboolean glIsEnabled(
    GLenum cap)
{
   return esIsEnabled(cap);
}
//
GLboolean (* esIsRenderbuffer)(GLuint renderbuffer) = 0;
__attribute__((visibility("default")))
GLboolean glIsRenderbuffer(
    GLuint renderbuffer)
{
   return esIsRenderbuffer(renderbuffer);
}
//
GLboolean (* esIsProgram)(GLuint program) = 0;
__attribute__((visibility("default")))
GLboolean glIsProgram(
    GLuint program)
{
   return esIsProgram(program);
}
//
GLboolean (* esIsShader)(GLuint shader) = 0;
__attribute__((visibility("default")))
GLboolean glIsShader(
    GLuint shader)
{
   return esIsShader(shader);
}
//
void (* esPolygonOffset)(GLfloat factor, GLfloat units) = 0;
__attribute__((visibility("default")))
void glPolygonOffset(
    GLfloat factor, 
    GLfloat units)
{
   (void) esPolygonOffset(factor, units);
}
//
void (* esLinkProgram)(GLuint program) = 0;
__attribute__((visibility("default")))
void glLinkProgram(
    GLuint program)
{
   (void) esLinkProgram(program);
}
//
void (* esLineWidth)(GLfloat width) = 0;
__attribute__((visibility("default")))
void glLineWidth(
    GLfloat width)
{
   (void) esLineWidth(width);
}
//
void (* esPixelStorei)(GLenum pname, GLint param) = 0;
__attribute__((visibility("default")))
void glPixelStorei(
    GLenum pname, 
    GLint param)
{
   (void) esPixelStorei(pname, param);
}
//
void (* esReleaseShaderCompiler)() = 0;
__attribute__((visibility("default")))
void glReleaseShaderCompiler(
)
{
   (void) esReleaseShaderCompiler();
}
//
void (* esReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels) = 0;
__attribute__((visibility("default")))
void glReadPixels(
    GLint x, 
    GLint y, 
    GLsizei width, 
    GLsizei height, 
    GLenum format, 
    GLenum type, 
    GLvoid * pixels)
{
   (void) esReadPixels(x, y, width, height, format, type, pixels);
}
//
void (* esRenderbufferStorage)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height) = 0;
__attribute__((visibility("default")))
void glRenderbufferStorage(
    GLenum target, 
    GLenum internalformat, 
    GLsizei width, 
    GLsizei height)
{
   (void) esRenderbufferStorage(target, internalformat, width, height);
}
//
void (* esUniform1f)(GLint location, GLfloat v0) = 0;
__attribute__((visibility("default")))
void glUniform1f(
    GLint location, 
    GLfloat v0)
{
   (void) esUniform1f(location, v0);
}
//
void (* esStencilOp)(GLenum fail, GLenum zfail, GLenum zpass) = 0;
__attribute__((visibility("default")))
void glStencilOp(
    GLenum fail, 
    GLenum zfail, 
    GLenum zpass)
{
   (void) esStencilOp(fail, zfail, zpass);
}
//
void (* esStencilFunc)(GLenum func, GLint ref, GLuint mask) = 0;
__attribute__((visibility("default")))
void glStencilFunc(
    GLenum func, 
    GLint ref, 
    GLuint mask)
{
   (void) esStencilFunc(func, ref, mask);
}
//
void (* esShaderBinary)(GLsizei n, const GLuint * shaders, GLenum binaryformat, const GLvoid * binary, GLsizei length) = 0;
__attribute__((visibility("default")))
void glShaderBinary(
    GLsizei n, 
    const GLuint * shaders, 
    GLenum binaryformat, 
    const GLvoid * binary, 
    GLsizei length)
{
   (void) esShaderBinary(n, shaders, binaryformat, binary, length);
}
//
void (* esScissor)(GLint x, GLint y, GLsizei width, GLsizei height) = 0;
__attribute__((visibility("default")))
void glScissor(
    GLint x, 
    GLint y, 
    GLsizei width, 
    GLsizei height)
{
   (void) esScissor(x, y, width, height);
}
//
void (* esShaderSource)(GLuint shader, GLsizei count, const GLchar * const * string, const GLint * length) = 0;
__attribute__((visibility("default")))
void glShaderSource(
    GLuint shader, 
    GLsizei count, 
    const GLchar * const * string, 
    const GLint * length);
//
void (* esStencilMask)(GLuint mask) = 0;
__attribute__((visibility("default")))
void glStencilMask(
    GLuint mask)
{
   (void) esStencilMask(mask);
}
//
void (* esStencilFuncSeparate)(GLenum face, GLenum func, GLint ref, GLuint mask) = 0;
__attribute__((visibility("default")))
void glStencilFuncSeparate(
    GLenum face, 
    GLenum func, 
    GLint ref, 
    GLuint mask)
{
   (void) esStencilFuncSeparate(face, func, ref, mask);
}
//
void (* esStencilMaskSeparate)(GLenum face, GLuint mask) = 0;
__attribute__((visibility("default")))
void glStencilMaskSeparate(
    GLenum face, 
    GLuint mask)
{
   (void) esStencilMaskSeparate(face, mask);
}
//
void (* esTexParameterfv)(GLenum target, GLenum pname, const GLfloat * params) = 0;
__attribute__((visibility("default")))
void glTexParameterfv(
    GLenum target, 
    GLenum pname, 
    const GLfloat * params)
{
   (void) esTexParameterfv(target, pname, params);
}
//
void (* esTexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels) = 0;
__attribute__((visibility("default")))
void glTexImage2D(
    GLenum target, 
    GLint level, 
    GLint internalformat, 
    GLsizei width, 
    GLsizei height, 
    GLint border, 
    GLenum format, 
    GLenum type, 
    const GLvoid * pixels)
{
   (void) esTexImage2D(target, level, internalformat, width, height, border, format, type, pixels);
}
//
void (* esStencilOpSeparate)(GLenum face, GLenum sfail, GLenum zfail, GLenum zpass) = 0;
__attribute__((visibility("default")))
void glStencilOpSeparate(
    GLenum face, 
    GLenum sfail, 
    GLenum zfail, 
    GLenum zpass)
{
   (void) esStencilOpSeparate(face, sfail, zfail, zpass);
}
//
void (* esTexParameterf)(GLenum target, GLenum pname, GLfloat param) = 0;
__attribute__((visibility("default")))
void glTexParameterf(
    GLenum target, 
    GLenum pname, 
    GLfloat param)
{
   (void) esTexParameterf(target, pname, param);
}
//
void (* esTexParameteriv)(GLenum target, GLenum pname, const GLint * params) = 0;
__attribute__((visibility("default")))
void glTexParameteriv(
    GLenum target, 
    GLenum pname, 
    const GLint * params)
{
   (void) esTexParameteriv(target, pname, params);
}
//
void (* esTexParameteri)(GLenum target, GLenum pname, GLint param) = 0;
__attribute__((visibility("default")))
void glTexParameteri(
    GLenum target, 
    GLenum pname, 
    GLint param)
{
   (void) esTexParameteri(target, pname, param);
}
//
void (* esTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels) = 0;
__attribute__((visibility("default")))
void glTexSubImage2D(
    GLenum target, 
    GLint level, 
    GLint xoffset, 
    GLint yoffset, 
    GLsizei width, 
    GLsizei height, 
    GLenum format, 
    GLenum type, 
    const GLvoid * pixels)
{
   (void) esTexSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels);
}
//
void (* esUniform3f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2) = 0;
__attribute__((visibility("default")))
void glUniform3f(
    GLint location, 
    GLfloat v0, 
    GLfloat v1, 
    GLfloat v2)
{
   (void) esUniform3f(location, v0, v1, v2);
}
//
void (* esUniform2f)(GLint location, GLfloat v0, GLfloat v1) = 0;
__attribute__((visibility("default")))
void glUniform2f(
    GLint location, 
    GLfloat v0, 
    GLfloat v1)
{
   (void) esUniform2f(location, v0, v1);
}
//
void (* esUniform1i)(GLint location, GLint v0) = 0;
__attribute__((visibility("default")))
void glUniform1i(
    GLint location, 
    GLint v0)
{
   (void) esUniform1i(location, v0);
}
//
void (* esUniform1fv)(GLint location, GLsizei count, const GLfloat * value) = 0;
__attribute__((visibility("default")))
void glUniform1fv(
    GLint location, 
    GLsizei count, 
    const GLfloat * value)
{
   (void) esUniform1fv(location, count, value);
}
//
void (* esUniform1iv)(GLint location, GLsizei count, const GLint * value) = 0;
__attribute__((visibility("default")))
void glUniform1iv(
    GLint location, 
    GLsizei count, 
    const GLint * value)
{
   (void) esUniform1iv(location, count, value);
}
//
void (* esUniform2i)(GLint location, GLint v0, GLint v1) = 0;
__attribute__((visibility("default")))
void glUniform2i(
    GLint location, 
    GLint v0, 
    GLint v1)
{
   (void) esUniform2i(location, v0, v1);
}
//
void (* esUniform2fv)(GLint location, GLsizei count, const GLfloat * value) = 0;
__attribute__((visibility("default")))
void glUniform2fv(
    GLint location, 
    GLsizei count, 
    const GLfloat * value)
{
   (void) esUniform2fv(location, count, value);
}
//
void (* esUniform2iv)(GLint location, GLsizei count, const GLint * value) = 0;
__attribute__((visibility("default")))
void glUniform2iv(
    GLint location, 
    GLsizei count, 
    const GLint * value)
{
   (void) esUniform2iv(location, count, value);
}
//
void (* esUniformMatrix2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) = 0;
__attribute__((visibility("default")))
void glUniformMatrix2fv(
    GLint location, 
    GLsizei count, 
    GLboolean transpose, 
    const GLfloat * value)
{
   (void) esUniformMatrix2fv(location, count, transpose, value);
}
//
void (* esUniform4f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) = 0;
__attribute__((visibility("default")))
void glUniform4f(
    GLint location, 
    GLfloat v0, 
    GLfloat v1, 
    GLfloat v2, 
    GLfloat v3)
{
   (void) esUniform4f(location, v0, v1, v2, v3);
}
//
void (* esUniform3i)(GLint location, GLint v0, GLint v1, GLint v2) = 0;
__attribute__((visibility("default")))
void glUniform3i(
    GLint location, 
    GLint v0, 
    GLint v1, 
    GLint v2)
{
   (void) esUniform3i(location, v0, v1, v2);
}
//
void (* esUniform3fv)(GLint location, GLsizei count, const GLfloat * value) = 0;
__attribute__((visibility("default")))
void glUniform3fv(
    GLint location, 
    GLsizei count, 
    const GLfloat * value)
{
   (void) esUniform3fv(location, count, value);
}
//
void (* esUniform3iv)(GLint location, GLsizei count, const GLint * value) = 0;
__attribute__((visibility("default")))
void glUniform3iv(
    GLint location, 
    GLsizei count, 
    const GLint * value)
{
   (void) esUniform3iv(location, count, value);
}
//
void (* esUniform4i)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3) = 0;
__attribute__((visibility("default")))
void glUniform4i(
    GLint location, 
    GLint v0, 
    GLint v1, 
    GLint v2, 
    GLint v3)
{
   (void) esUniform4i(location, v0, v1, v2, v3);
}
//
void (* esUniform4fv)(GLint location, GLsizei count, const GLfloat * value) = 0;
__attribute__((visibility("default")))
void glUniform4fv(
    GLint location, 
    GLsizei count, 
    const GLfloat * value)
{
   (void) esUniform4fv(location, count, value);
}
//
void (* esUniform4iv)(GLint location, GLsizei count, const GLint * value) = 0;
__attribute__((visibility("default")))
void glUniform4iv(
    GLint location, 
    GLsizei count, 
    const GLint * value)
{
   (void) esUniform4iv(location, count, value);
}
//
void (* esValidateProgram)(GLuint program) = 0;
__attribute__((visibility("default")))
void glValidateProgram(
    GLuint program)
{
   (void) esValidateProgram(program);
}
//
void (* esUniformMatrix4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) = 0;
__attribute__((visibility("default")))
void glUniformMatrix4fv(
    GLint location, 
    GLsizei count, 
    GLboolean transpose, 
    const GLfloat * value)
{
   (void) esUniformMatrix4fv(location, count, transpose, value);
}
//
void (* esUniformMatrix3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) = 0;
__attribute__((visibility("default")))
void glUniformMatrix3fv(
    GLint location, 
    GLsizei count, 
    GLboolean transpose, 
    const GLfloat * value)
{
   (void) esUniformMatrix3fv(location, count, transpose, value);
}
//
void (* esUseProgram)(GLuint program) = 0;
__attribute__((visibility("default")))
void glUseProgram(
    GLuint program)
{
   (void) esUseProgram(program);
}
//
void (* esVertexAttrib2fv)(GLuint index, const GLfloat * v) = 0;
__attribute__((visibility("default")))
void glVertexAttrib2fv(
    GLuint index, 
    const GLfloat * v)
{
   (void) esVertexAttrib2fv(index, v);
}
//
void (* esVertexAttrib1fv)(GLuint index, const GLfloat * v) = 0;
__attribute__((visibility("default")))
void glVertexAttrib1fv(
    GLuint index, 
    const GLfloat * v)
{
   (void) esVertexAttrib1fv(index, v);
}
//
void (* esVertexAttrib1f)(GLuint index, GLfloat x) = 0;
__attribute__((visibility("default")))
void glVertexAttrib1f(
    GLuint index, 
    GLfloat x)
{
   (void) esVertexAttrib1f(index, x);
}
//
void (* esVertexAttrib2f)(GLuint index, GLfloat x, GLfloat y) = 0;
__attribute__((visibility("default")))
void glVertexAttrib2f(
    GLuint index, 
    GLfloat x, 
    GLfloat y)
{
   (void) esVertexAttrib2f(index, x, y);
}
//
void (* esVertexAttrib3fv)(GLuint index, const GLfloat * v) = 0;
__attribute__((visibility("default")))
void glVertexAttrib3fv(
    GLuint index, 
    const GLfloat * v)
{
   (void) esVertexAttrib3fv(index, v);
}
//
void (* esVertexAttrib3f)(GLuint index, GLfloat x, GLfloat y, GLfloat z) = 0;
__attribute__((visibility("default")))
void glVertexAttrib3f(
    GLuint index, 
    GLfloat x, 
    GLfloat y, 
    GLfloat z)
{
   (void) esVertexAttrib3f(index, x, y, z);
}
//
void (* esVertexAttrib4fv)(GLuint index, const GLfloat * v) = 0;
__attribute__((visibility("default")))
void glVertexAttrib4fv(
    GLuint index, 
    const GLfloat * v)
{
   (void) esVertexAttrib4fv(index, v);
}
//
void (* esVertexAttrib4f)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) = 0;
__attribute__((visibility("default")))
void glVertexAttrib4f(
    GLuint index, 
    GLfloat x, 
    GLfloat y, 
    GLfloat z, 
    GLfloat w)
{
   (void) esVertexAttrib4f(index, x, y, z, w);
}
//
void (* esVertexAttribPointer)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid * pointer) = 0;
__attribute__((visibility("default")))
void glVertexAttribPointer(
    GLuint index, 
    GLint size, 
    GLenum type, 
    GLboolean normalized, 
    GLsizei stride, 
    const GLvoid * pointer)
{
   (void) esVertexAttribPointer(index, size, type, normalized, stride, pointer);
}
//
void (* esViewport)(GLint x, GLint y, GLsizei width, GLsizei height) = 0;
__attribute__((visibility("default")))
void glViewport(
    GLint x, 
    GLint y, 
    GLsizei width, 
    GLsizei height)
{
   (void) esViewport(x, y, width, height);
}
// ----------------------------------------------------------------- //
#ifdef __WAJIC__
#define LINK(name) es##name = dlsym(GLES, "JS" #name)
#else
#define LINK(name) es##name = dlsym(GLES, "gl" #name)
#endif

extern void Init(void); // internal, call from gl2esInit() only

#include <dlfcn.h>
void* GLES = 0;
#ifdef __WAJIC__
WA_EXPORT(gl2esInit)
#else
__attribute__((visibility("default")))
#endif
void gl2esInit() {
   // if (GLES != 0) return;
   GLES = dlopen("libGLESv2.so", RTLD_LAZY);

   LINK(GetIntegerv);
   LINK(DeleteRenderbuffers);
   LINK(Clear);
   LINK(BlendColor);
   LINK(BindBuffer);
   LINK(AttachShader);
   LINK(ActiveTexture);
   LINK(BindAttribLocation);
   LINK(BindRenderbuffer);
   LINK(BindFramebuffer);
   LINK(BindTexture);
   LINK(BlendFuncSeparate);
   LINK(BlendEquationSeparate);
   LINK(BlendEquation);
   LINK(BlendFunc);
   LINK(BufferSubData);
   LINK(BufferData);
   LINK(CheckFramebufferStatus);
   LINK(CopyTexImage2D);
   LINK(ColorMask);
   LINK(ClearDepthf);
   LINK(ClearColor);
   LINK(ClearStencil);
   LINK(CompressedTexImage2D);
   LINK(CompileShader);
   LINK(CompressedTexSubImage2D);
   LINK(CullFace);
   LINK(CreateProgram);
   LINK(CopyTexSubImage2D);
   LINK(CreateShader);
   LINK(DeleteFramebuffers);
   LINK(DeleteBuffers);
   LINK(DeleteProgram);
   LINK(FramebufferTexture2D);
   LINK(DisableVertexAttribArray);
   LINK(DepthMask);
   LINK(DeleteTextures);
   LINK(DeleteShader);
   LINK(DepthFunc);
   LINK(DetachShader);
   LINK(DepthRangef);
   LINK(Disable);
   LINK(EnableVertexAttribArray);
   LINK(DrawElements);
   LINK(DrawArrays);
   LINK(Enable);
   LINK(Flush);
   LINK(Finish);
   LINK(FramebufferRenderbuffer);
   LINK(GetActiveUniform);
   LINK(GenRenderbuffers);
   LINK(GenBuffers);
   LINK(FrontFace);
   LINK(GenFramebuffers);
   LINK(GenerateMipmap);
   LINK(GenTextures);
   LINK(GetActiveAttrib);
   LINK(GetBufferParameteriv);
   LINK(GetAttribLocation);
   LINK(GetAttachedShaders);
   LINK(GetBooleanv);
   LINK(GetFloatv);
   LINK(GetError);
   LINK(GetFramebufferAttachmentParameteriv);
   LINK(SampleCoverage);
   LINK(GetVertexAttribiv);
   LINK(GetString);
   LINK(GetShaderInfoLog);
   LINK(GetProgramiv);
   LINK(GetProgramInfoLog);
   LINK(GetRenderbufferParameteriv);
   LINK(GetShaderSource);
   LINK(GetShaderPrecisionFormat);
   LINK(GetShaderiv);
   LINK(GetUniformfv);
   LINK(GetTexParameteriv);
   LINK(GetTexParameterfv);
   LINK(GetUniformLocation);
   LINK(GetVertexAttribPointerv);
   LINK(GetUniformiv);
   LINK(GetVertexAttribfv);
   LINK(IsTexture);
   LINK(IsFramebuffer);
   LINK(IsBuffer);
   LINK(Hint);
   LINK(IsEnabled);
   LINK(IsRenderbuffer);
   LINK(IsProgram);
   LINK(IsShader);
   LINK(PolygonOffset);
   LINK(LinkProgram);
   LINK(LineWidth);
   LINK(PixelStorei);
   LINK(ReleaseShaderCompiler);
   LINK(ReadPixels);
   LINK(RenderbufferStorage);
   LINK(Uniform1f);
   LINK(StencilOp);
   LINK(StencilFunc);
   LINK(ShaderBinary);
   LINK(Scissor);
   LINK(ShaderSource);
   LINK(StencilMask);
   LINK(StencilFuncSeparate);
   LINK(StencilMaskSeparate);
   LINK(TexParameterfv);
   LINK(TexImage2D);
   LINK(StencilOpSeparate);
   LINK(TexParameterf);
   LINK(TexParameteriv);
   LINK(TexParameteri);
   LINK(TexSubImage2D);
   LINK(Uniform3f);
   LINK(Uniform2f);
   LINK(Uniform1i);
   LINK(Uniform1fv);
   LINK(Uniform1iv);
   LINK(Uniform2i);
   LINK(Uniform2fv);
   LINK(Uniform2iv);
   LINK(UniformMatrix2fv);
   LINK(Uniform4f);
   LINK(Uniform3i);
   LINK(Uniform3fv);
   LINK(Uniform3iv);
   LINK(Uniform4i);
   LINK(Uniform4fv);
   LINK(Uniform4iv);
   LINK(ValidateProgram);
   LINK(UniformMatrix4fv);
   LINK(UniformMatrix3fv);
   LINK(UseProgram);
   LINK(VertexAttrib2fv);
   LINK(VertexAttrib1fv);
   LINK(VertexAttrib1f);
   LINK(VertexAttrib2f);
   LINK(VertexAttrib3fv);
   LINK(VertexAttrib3f);
   LINK(VertexAttrib4fv);
   LINK(VertexAttrib4f);
   LINK(VertexAttribPointer);
   LINK(Viewport);

   Init();
}
